/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as EnterVerifyRouteImport } from './routes/enter.verify'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedScanIndexRouteImport } from './routes/_authenticated/scan/index'
import { Route as AuthenticatedScanStartRouteImport } from './routes/_authenticated/scan/start'
import { Route as AuthenticatedProfileScansRouteImport } from './routes/_authenticated/profile/scans'
import { Route as ApiPublicShareCardPostIdRouteImport } from './routes/api/public/share-card.$postId'
import { Route as ApiPublicSPostIdRouteImport } from './routes/api/public/s.$postId'
import { Route as AuthenticatedScanResultScanIdRouteImport } from './routes/_authenticated/scan/result.$scanId'
import { Route as AuthenticatedScanQuestionStepRouteImport } from './routes/_authenticated/scan/question.$step'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterVerifyRoute = EnterVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => EnterRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanIndexRoute = AuthenticatedScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanStartRoute = AuthenticatedScanStartRouteImport.update({
  id: '/scan/start',
  path: '/scan/start',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileScansRoute =
  AuthenticatedProfileScansRouteImport.update({
    id: '/profile/scans',
    path: '/profile/scans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicShareCardPostIdRoute =
  ApiPublicShareCardPostIdRouteImport.update({
    id: '/api/public/share-card/$postId',
    path: '/api/public/share-card/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSPostIdRoute = ApiPublicSPostIdRouteImport.update({
  id: '/api/public/s/$postId',
  path: '/api/public/s/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanResultScanIdRoute =
  AuthenticatedScanResultScanIdRouteImport.update({
    id: '/scan/result/$scanId',
    path: '/scan/result/$scanId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScanQuestionStepRoute =
  AuthenticatedScanQuestionStepRouteImport.update({
    id: '/scan/question/$step',
    path: '/scan/question/$step',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enter': typeof EnterRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/enter/verify': typeof EnterVerifyRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/scans': typeof AuthenticatedProfileScansRoute
  '/scan/start': typeof AuthenticatedScanStartRoute
  '/scan/': typeof AuthenticatedScanIndexRoute
  '/scan/question/$step': typeof AuthenticatedScanQuestionStepRoute
  '/scan/result/$scanId': typeof AuthenticatedScanResultScanIdRoute
  '/api/public/s/$postId': typeof ApiPublicSPostIdRoute
  '/api/public/share-card/$postId': typeof ApiPublicShareCardPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enter': typeof EnterRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/enter/verify': typeof EnterVerifyRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/scans': typeof AuthenticatedProfileScansRoute
  '/scan/start': typeof AuthenticatedScanStartRoute
  '/scan': typeof AuthenticatedScanIndexRoute
  '/scan/question/$step': typeof AuthenticatedScanQuestionStepRoute
  '/scan/result/$scanId': typeof AuthenticatedScanResultScanIdRoute
  '/api/public/s/$postId': typeof ApiPublicSPostIdRoute
  '/api/public/share-card/$postId': typeof ApiPublicShareCardPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/enter': typeof EnterRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/enter/verify': typeof EnterVerifyRoute
  '/post/$postId': typeof PostPostIdRoute
  '/_authenticated/profile/scans': typeof AuthenticatedProfileScansRoute
  '/_authenticated/scan/start': typeof AuthenticatedScanStartRoute
  '/_authenticated/scan/': typeof AuthenticatedScanIndexRoute
  '/_authenticated/scan/question/$step': typeof AuthenticatedScanQuestionStepRoute
  '/_authenticated/scan/result/$scanId': typeof AuthenticatedScanResultScanIdRoute
  '/api/public/s/$postId': typeof ApiPublicSPostIdRoute
  '/api/public/share-card/$postId': typeof ApiPublicShareCardPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enter'
    | '/welcome'
    | '/compose'
    | '/enter/verify'
    | '/post/$postId'
    | '/profile/scans'
    | '/scan/start'
    | '/scan/'
    | '/scan/question/$step'
    | '/scan/result/$scanId'
    | '/api/public/s/$postId'
    | '/api/public/share-card/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enter'
    | '/welcome'
    | '/compose'
    | '/enter/verify'
    | '/post/$postId'
    | '/profile/scans'
    | '/scan/start'
    | '/scan'
    | '/scan/question/$step'
    | '/scan/result/$scanId'
    | '/api/public/s/$postId'
    | '/api/public/share-card/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/enter'
    | '/welcome'
    | '/_authenticated/compose'
    | '/enter/verify'
    | '/post/$postId'
    | '/_authenticated/profile/scans'
    | '/_authenticated/scan/start'
    | '/_authenticated/scan/'
    | '/_authenticated/scan/question/$step'
    | '/_authenticated/scan/result/$scanId'
    | '/api/public/s/$postId'
    | '/api/public/share-card/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EnterRoute: typeof EnterRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ApiPublicSPostIdRoute: typeof ApiPublicSPostIdRoute
  ApiPublicShareCardPostIdRoute: typeof ApiPublicShareCardPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter/verify': {
      id: '/enter/verify'
      path: '/verify'
      fullPath: '/enter/verify'
      preLoaderRoute: typeof EnterVerifyRouteImport
      parentRoute: typeof EnterRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/': {
      id: '/_authenticated/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof AuthenticatedScanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/start': {
      id: '/_authenticated/scan/start'
      path: '/scan/start'
      fullPath: '/scan/start'
      preLoaderRoute: typeof AuthenticatedScanStartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/scans': {
      id: '/_authenticated/profile/scans'
      path: '/profile/scans'
      fullPath: '/profile/scans'
      preLoaderRoute: typeof AuthenticatedProfileScansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/share-card/$postId': {
      id: '/api/public/share-card/$postId'
      path: '/api/public/share-card/$postId'
      fullPath: '/api/public/share-card/$postId'
      preLoaderRoute: typeof ApiPublicShareCardPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/s/$postId': {
      id: '/api/public/s/$postId'
      path: '/api/public/s/$postId'
      fullPath: '/api/public/s/$postId'
      preLoaderRoute: typeof ApiPublicSPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan/result/$scanId': {
      id: '/_authenticated/scan/result/$scanId'
      path: '/scan/result/$scanId'
      fullPath: '/scan/result/$scanId'
      preLoaderRoute: typeof AuthenticatedScanResultScanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/question/$step': {
      id: '/_authenticated/scan/question/$step'
      path: '/scan/question/$step'
      fullPath: '/scan/question/$step'
      preLoaderRoute: typeof AuthenticatedScanQuestionStepRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedProfileScansRoute: typeof AuthenticatedProfileScansRoute
  AuthenticatedScanStartRoute: typeof AuthenticatedScanStartRoute
  AuthenticatedScanIndexRoute: typeof AuthenticatedScanIndexRoute
  AuthenticatedScanQuestionStepRoute: typeof AuthenticatedScanQuestionStepRoute
  AuthenticatedScanResultScanIdRoute: typeof AuthenticatedScanResultScanIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedProfileScansRoute: AuthenticatedProfileScansRoute,
  AuthenticatedScanStartRoute: AuthenticatedScanStartRoute,
  AuthenticatedScanIndexRoute: AuthenticatedScanIndexRoute,
  AuthenticatedScanQuestionStepRoute: AuthenticatedScanQuestionStepRoute,
  AuthenticatedScanResultScanIdRoute: AuthenticatedScanResultScanIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EnterRouteChildren {
  EnterVerifyRoute: typeof EnterVerifyRoute
}

const EnterRouteChildren: EnterRouteChildren = {
  EnterVerifyRoute: EnterVerifyRoute,
}

const EnterRouteWithChildren = EnterRoute._addFileChildren(EnterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EnterRoute: EnterRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  PostPostIdRoute: PostPostIdRoute,
  ApiPublicSPostIdRoute: ApiPublicSPostIdRoute,
  ApiPublicShareCardPostIdRoute: ApiPublicShareCardPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
