/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as EnterVerifyRouteImport } from './routes/enter.verify'
import { Route as ApiPublicShareCardPostIdRouteImport } from './routes/api/public/share-card.$postId'
import { Route as ApiPublicSPostIdRouteImport } from './routes/api/public/s.$postId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterVerifyRoute = EnterVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => EnterRoute,
} as any)
const ApiPublicShareCardPostIdRoute =
  ApiPublicShareCardPostIdRouteImport.update({
    id: '/api/public/share-card/$postId',
    path: '/api/public/share-card/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSPostIdRoute = ApiPublicSPostIdRouteImport.update({
  id: '/api/public/s/$postId',
  path: '/api/public/s/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/enter': typeof EnterRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/enter/verify': typeof EnterVerifyRoute
  '/post/$postId': typeof PostPostIdRoute
  '/api/public/s/$postId': typeof ApiPublicSPostIdRoute
  '/api/public/share-card/$postId': typeof ApiPublicShareCardPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/enter': typeof EnterRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/enter/verify': typeof EnterVerifyRoute
  '/post/$postId': typeof PostPostIdRoute
  '/api/public/s/$postId': typeof ApiPublicSPostIdRoute
  '/api/public/share-card/$postId': typeof ApiPublicShareCardPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/enter': typeof EnterRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/enter/verify': typeof EnterVerifyRoute
  '/post/$postId': typeof PostPostIdRoute
  '/api/public/s/$postId': typeof ApiPublicSPostIdRoute
  '/api/public/share-card/$postId': typeof ApiPublicShareCardPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compose'
    | '/enter'
    | '/welcome'
    | '/enter/verify'
    | '/post/$postId'
    | '/api/public/s/$postId'
    | '/api/public/share-card/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compose'
    | '/enter'
    | '/welcome'
    | '/enter/verify'
    | '/post/$postId'
    | '/api/public/s/$postId'
    | '/api/public/share-card/$postId'
  id:
    | '__root__'
    | '/'
    | '/compose'
    | '/enter'
    | '/welcome'
    | '/enter/verify'
    | '/post/$postId'
    | '/api/public/s/$postId'
    | '/api/public/share-card/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposeRoute: typeof ComposeRoute
  EnterRoute: typeof EnterRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ApiPublicSPostIdRoute: typeof ApiPublicSPostIdRoute
  ApiPublicShareCardPostIdRoute: typeof ApiPublicShareCardPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter/verify': {
      id: '/enter/verify'
      path: '/verify'
      fullPath: '/enter/verify'
      preLoaderRoute: typeof EnterVerifyRouteImport
      parentRoute: typeof EnterRoute
    }
    '/api/public/share-card/$postId': {
      id: '/api/public/share-card/$postId'
      path: '/api/public/share-card/$postId'
      fullPath: '/api/public/share-card/$postId'
      preLoaderRoute: typeof ApiPublicShareCardPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/s/$postId': {
      id: '/api/public/s/$postId'
      path: '/api/public/s/$postId'
      fullPath: '/api/public/s/$postId'
      preLoaderRoute: typeof ApiPublicSPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnterRouteChildren {
  EnterVerifyRoute: typeof EnterVerifyRoute
}

const EnterRouteChildren: EnterRouteChildren = {
  EnterVerifyRoute: EnterVerifyRoute,
}

const EnterRouteWithChildren = EnterRoute._addFileChildren(EnterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposeRoute: ComposeRoute,
  EnterRoute: EnterRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  PostPostIdRoute: PostPostIdRoute,
  ApiPublicSPostIdRoute: ApiPublicSPostIdRoute,
  ApiPublicShareCardPostIdRoute: ApiPublicShareCardPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
